/**
 * PDF Export Utility — uses browser print window (no npm packages needed).
 * Creates a clean printable HTML page and triggers the print dialog.
 */

const baseStyles = `
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Inter', Arial, sans-serif;
    padding: 40px;
    color: #1a1a2e;
    font-size: 14px;
    line-height: 1.6;
  }
  h1 { font-size: 24px; font-weight: 700; color: #4f46e5; margin-bottom: 6px; }
  h2 { font-size: 18px; font-weight: 600; margin: 20px 0 10px; color: #374151; }
  h3 { font-size: 15px; font-weight: 600; margin: 14px 0 6px; color: #1f2937; }
  p { margin-bottom: 8px; }
  .meta { color: #6b7280; font-size: 12px; margin-bottom: 24px; }
  .header-bar {
    display: flex; align-items: center; justify-content: space-between;
    border-bottom: 3px solid #4f46e5; padding-bottom: 16px; margin-bottom: 24px;
  }
  .logo { font-size: 16px; font-weight: 700; color: #4f46e5; }
  @media print {
    body { padding: 20px; }
    .no-print { display: none; }
  }
`;

const header = (title, subtitle) => `
  <div class="header-bar">
    <div>
      <h1>${title}</h1>
      <p class="meta">${subtitle} &nbsp;|&nbsp; Generated by AI Study Planner &nbsp;|&nbsp; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    </div>
    <div class="logo">📚 AI Study Planner</div>
  </div>
`;

const openPrintWindow = (title, bodyHtml) => {
  const win = window.open('', '_blank');
  if (!win) { alert('Please allow popups to export PDF.'); return; }
  win.document.write(`<!DOCTYPE html><html><head>
    <meta charset="UTF-8">
    <title>${title} — AI Study Planner</title>
    <style>${baseStyles}</style>
  </head><body>${bodyHtml}<script>window.onload=()=>{window.print();}<\/script></body></html>`);
  win.document.close();
};

// ── Export Summary ────────────────────────────────────────────────────────────
export const exportSummaryPDF = (summaryText, originalLength) => {
  const body = `
    ${header('Notes Summary', `Original: ${originalLength} chars`)}
    <div style="background:#f0f4ff;border-left:4px solid #4f46e5;padding:20px;border-radius:8px;white-space:pre-wrap;">${summaryText.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</div>
  `;
  openPrintWindow('Notes Summary', body);
};

// ── Export Flashcards ─────────────────────────────────────────────────────────
export const exportFlashcardsPDF = (flashcards, topicTitle) => {
  const cards = flashcards.map((card, i) => `
    <div style="border:1px solid #e5e7eb;border-radius:10px;padding:16px 20px;margin-bottom:14px;page-break-inside:avoid;">
      <div style="display:flex;align-items:start;gap:12px;">
        <span style="background:#4f46e5;color:white;font-weight:700;border-radius:6px;padding:2px 10px;font-size:13px;flex-shrink:0;">Q${i + 1}</span>
        <div>
          <p style="font-weight:600;color:#1f2937;margin-bottom:8px;">${card.question.replace(/</g,'&lt;')}</p>
          <div style="background:#f0fdf4;border-left:3px solid #22c55e;padding:10px 14px;border-radius:6px;">
            <p style="color:#166534;font-size:13px;">${card.answer.replace(/</g,'&lt;')}</p>
          </div>
        </div>
      </div>
    </div>
  `).join('');

  const body = `
    ${header('Flashcards', topicTitle || `${flashcards.length} cards`)}
    <p style="color:#6b7280;margin-bottom:16px;">Total: ${flashcards.length} flashcards</p>
    ${cards}
  `;
  openPrintWindow('Flashcards', body);
};

// ── Export AI Assistant Chat ──────────────────────────────────────────────────
export const exportChatPDF = (messages, topic) => {
  const msgs = messages.map(m => `
    <div style="margin-bottom:14px;${m.type === 'user' ? 'text-align:right;' : ''}">
      <div style="display:inline-block;max-width:80%;text-align:left;padding:12px 16px;border-radius:12px;
        ${m.type === 'user'
          ? 'background:#4f46e5;color:white;'
          : 'background:#f3f4f6;color:#1f2937;border:1px solid #e5e7eb;'}
        white-space:pre-wrap;font-size:13px;line-height:1.6;">
        <strong style="display:block;font-size:11px;margin-bottom:4px;opacity:0.7;">
          ${m.type === 'user' ? 'You' : '🤖 AI Assistant'} &nbsp;·&nbsp; ${m.timestamp||''}
        </strong>
        ${m.content.replace(/</g,'&lt;').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')}
      </div>
    </div>
  `).join('');

  const body = `${header('AI Assistant Conversation', topic || 'Chat Export')}<div>${msgs}</div>`;
  openPrintWindow('AI Chat Export', body);
};

// ── Export Quiz Results ───────────────────────────────────────────────────────
export const exportQuizPDF = (questions, answers, score, total) => {
  const rows = questions.map((q, i) => {
    const userAns = answers[i];
    const correct = userAns === q.correct_answer;
    return `
      <div style="border:1px solid #e5e7eb;border-radius:10px;padding:16px;margin-bottom:12px;page-break-inside:avoid;
        border-left:4px solid ${correct?'#22c55e':'#ef4444'};">
        <p style="font-weight:600;margin-bottom:10px;">${i+1}. ${q.question.replace(/</g,'&lt;')}</p>
        <p style="color:${correct?'#16a34a':'#dc2626'};font-size:13px;margin-bottom:4px;">
          ${correct?'✓':'✗'} Your answer: <strong>${userAns||'(skipped)'}</strong>
        </p>
        ${!correct?`<p style="color:#16a34a;font-size:13px;">Correct: <strong>${q.correct_answer}</strong></p>`:''}
        ${q.explanation?`<p style="color:#6b7280;font-size:12px;margin-top:8px;font-style:italic;">💡 ${q.explanation}</p>`:''}
      </div>
    `;
  }).join('');

  const pct = Math.round((score/total)*100);
  const body = `
    ${header('Quiz Results', `Score: ${score}/${total} (${pct}%)`)}
    <div style="background:${pct>=70?'#f0fdf4':'#fef2f2'};border-radius:12px;padding:20px;margin-bottom:24px;text-align:center;">
      <p style="font-size:40px;font-weight:700;color:${pct>=70?'#16a34a':'#dc2626'};">${pct}%</p>
      <p style="color:#6b7280;">${score} correct out of ${total} questions</p>
    </div>
    ${rows}
  `;
  openPrintWindow('Quiz Results', body);
};

// ── Export Study Plan ─────────────────────────────────────────────────────────
export const exportStudyPlanPDF = (plan) => {
  const schedule = (plan.schedule || []).map((day, i) => `
    <div style="border:1px solid #e5e7eb;border-radius:10px;padding:14px 18px;margin-bottom:10px;page-break-inside:avoid;">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
        <h3 style="margin:0;">Day ${day.day} — ${day.focus||''}</h3>
        <span style="background:#ede9fe;color:#7c3aed;padding:2px 10px;border-radius:20px;font-size:12px;font-weight:600;">${day.duration||''}</span>
      </div>
      ${day.topics?.length ? `<p style="margin-bottom:6px;color:#374151;font-size:13px;">📌 Topics: ${day.topics.join(', ')}</p>` : ''}
      ${day.tips ? `<p style="color:#6b7280;font-size:12px;font-style:italic;">💡 ${day.tips}</p>` : ''}
    </div>
  `).join('');

  const body = `
    ${header('Study Plan', plan.overview || '')}
    <div style="display:flex;gap:20px;margin-bottom:20px;">
      <div style="background:#ede9fe;padding:12px 20px;border-radius:10px;text-align:center;">
        <p style="font-size:22px;font-weight:700;color:#7c3aed;">${plan.total_days||'?'}</p>
        <p style="font-size:12px;color:#7c3aed;">Days</p>
      </div>
      <div style="background:#dbeafe;padding:12px 20px;border-radius:10px;text-align:center;">
        <p style="font-size:22px;font-weight:700;color:#1d4ed8;">${plan.total_topics||'?'}</p>
        <p style="font-size:12px;color:#1d4ed8;">Topics</p>
      </div>
    </div>
    ${schedule}
  `;
  openPrintWindow('Study Plan', body);
};
